---
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          command: |
            echo "Deploy Deploy Deploy"
            #cd nginx-static
            #docker-compose build
workflows:
  test:
    jobs:
      - build
