---
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run:
          command: |
            echo "Hello world!"
            docker-compose
workflows:
  test:
    jobs:
      - build
