version: 2.1
jobs:
  build:
    docker:
      - image: nginx:1.21.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout # check out the code in the project directory
      - run: echo "Hello World" # run the `echo` command

